apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./kube-state-metrics-clusterRole.yaml
  - ./kube-state-metrics-clusterRoleBinding.yaml
  - ./kube-state-metrics-deployment.yaml
  - ./kube-state-metrics-prometheusRule.yaml
  - ./kube-state-metrics-service.yaml
  - ./kube-state-metrics-serviceAccount.yaml
  - ./kube-state-metrics-serviceMonitor.yaml
  - ./kubernetes-prometheusRule.yaml
  - ./kubernetes-serviceMonitorApiserver.yaml
  - ./kubernetes-serviceMonitorCoreDNS.yaml
  - ./kubernetes-serviceMonitorKubeControllerManager.yaml
  - ./kubernetes-serviceMonitorKubeScheduler.yaml
  - ./kubernetes-serviceMonitorKubelet.yaml
  - ./node-exporter-clusterRole.yaml
  - ./node-exporter-clusterRoleBinding.yaml
  - ./node-exporter-daemonset.yaml
  - ./node-exporter-prometheusRule.yaml
  - ./node-exporter-service.yaml
  - ./node-exporter-serviceAccount.yaml
  - ./node-exporter-serviceMonitor.yaml
  - ./prometheus-adapter-apiService.yaml
  - ./prometheus-adapter-clusterRole.yaml
  - ./prometheus-adapter-clusterRoleAggregatedMetricsReader.yaml
  - ./prometheus-adapter-clusterRoleBinding.yaml
  - ./prometheus-adapter-clusterRoleBindingDelegator.yaml
  - ./prometheus-adapter-clusterRoleServerResources.yaml
  - ./prometheus-adapter-configMap.yaml
  - ./prometheus-adapter-deployment.yaml
  - ./prometheus-adapter-podDisruptionBudget.yaml
  - ./prometheus-adapter-roleBindingAuthReader.yaml
  - ./prometheus-adapter-service.yaml
  - ./prometheus-adapter-serviceAccount.yaml
  - ./prometheus-adapter-serviceMonitor.yaml
  - ./prometheus-clusterRole.yaml
  - ./prometheus-clusterRoleBinding.yaml
  - ./prometheus-operator-serviceMonitor.yaml
  - ./prometheus-podDisruptionBudget.yaml
  - ./prometheus-prometheus.yaml
  - ./prometheus-prometheusRule.yaml
  - ./prometheus-roleBindingConfig.yaml
  - ./prometheus-roleBindingSpecificNamespaces.yaml
  - ./prometheus-roleConfig.yaml
  - ./prometheus-roleSpecificNamespaces.yaml
  - ./prometheus-service.yaml
  - ./prometheus-serviceAccount.yaml
  - ./prometheus-serviceMonitor.yaml
  - ./setup/0namespace-namespace.yaml
  - ./setup/prometheus-operator-0alertmanagerConfigCustomResourceDefinition.yaml
  - ./setup/prometheus-operator-0alertmanagerCustomResourceDefinition.yaml
  - ./setup/prometheus-operator-0podmonitorCustomResourceDefinition.yaml
  - ./setup/prometheus-operator-0probeCustomResourceDefinition.yaml
  - ./setup/prometheus-operator-0prometheusCustomResourceDefinition.yaml
  - ./setup/prometheus-operator-0prometheusagentCustomResourceDefinition.yaml
  - ./setup/prometheus-operator-0prometheusruleCustomResourceDefinition.yaml
  - ./setup/prometheus-operator-0scrapeconfigCustomResourceDefinition.yaml
  - ./setup/prometheus-operator-0servicemonitorCustomResourceDefinition.yaml
  - ./setup/prometheus-operator-clusterRole.yaml
  - ./setup/prometheus-operator-clusterRoleBinding.yaml
  - ./setup/prometheus-operator-deployment.yaml
  - ./setup/prometheus-operator-service.yaml
  - ./setup/prometheus-operator-serviceAccount.yaml
